import { defineCollection, z } from "astro:content";
import { glob } from "astro/loaders";

const blog = defineCollection({
  loader: glob({ pattern: "**/*.md", base: "./src/content/blog" }),
  schema: z.object({
    title:         z.string(),
    description:   z.string(),
    date:          z.coerce.date(),
    draft:         z.boolean().default(false),
    tags:          z.array(z.string()).default([]),
    category:      z.string().optional(),
    sourceUrl:     z.string().url().optional(),
    sourceName:    z.string().optional(),
    autogenerated: z.boolean().default(false),
  }),
});

const labs = defineCollection({
  loader: glob({ pattern: "**/*.md", base: "./src/content/labs" }),
  schema: z.object({
    title: z.string(),
    description: z.string(),
    date: z.coerce.date(),
    draft: z.boolean().default(false),
    stack: z.array(z.string()).default([]),
    cover: z.string().optional(),
  }),
});

const briefing = defineCollection({
  loader: glob({ pattern: "**/*.md", base: "./src/content/briefing" }),
  schema: z.object({
    title: z.string(),
    description: z.string(),
    date: z.coerce.date(),
    draft: z.boolean().default(false),
    source: z.string().optional(),
  }),
});

export const collections = {
  blog,
  labs,
  briefing,
};