import { defineCollection, z } from "astro:content";
import { glob } from "astro/loaders";

const blog = defineCollection({
  loader: glob({ pattern: "**/*.md", base: "./src/content/blog" }),
  schema: z.object({
    title:         z.string(),
    description:   z.string(),
    date:          z.coerce.date(),
    draft:         z.boolean().default(false),
    tags:          z.array(z.string()).default([]),
    category:      z.string().optional(),
    sourceUrl:     z.string().url().optional(),
    sourceName:    z.string().optional(),
    autogenerated: z.boolean().default(false),
  }),
});

const labs = defineCollection({
  loader: glob({ pattern: "**/*.md", base: "./src/content/labs" }),
  schema: z.object({
    title:       z.string(),
    description: z.string(),
    date:        z.coerce.date(),
    draft:       z.boolean().default(false),
    stack:       z.array(z.string()).default([]),
    cover:       z.string().optional(),
    difficulty:  z.enum(['beginner', 'intermediate', 'advanced']).optional(),
    labType:     z.enum(['hands-on', 'architecture', 'devops', 'security']).optional(),
    source:      z.string().url().optional(),
    sourceName:  z.string().optional(),
  }),
});

const briefing = defineCollection({
  loader: glob({ pattern: "**/*.md", base: "./src/content/briefing" }),
  schema: z.object({
    title: z.string(),
    description: z.string(),
    date: z.coerce.date(),
    draft: z.boolean().default(false),
    source: z.string().optional(),
  }),
});

const projects = defineCollection({
  loader: glob({ pattern: "**/*.md", base: "./src/content/projects" }),
  schema: z.object({
    title:       z.string(),
    description: z.string(),
    date:        z.coerce.date(),
    draft:       z.boolean().default(false),
    stack:       z.array(z.string()).default([]),
    status:      z.enum(['live', 'in-progress', 'archived', 'planned']).default('in-progress'),
    category:    z.enum(['infrastructure', 'automation', 'platform', 'web', 'data', 'other']).default('other'),
    featured:    z.boolean().default(false),
    repoUrl:     z.string().url().optional(),
    liveUrl:     z.string().url().optional(),
    cover:       z.string().optional(),
    highlights:  z.array(z.string()).default([]),
  }),
});

export const collections = {
  blog,
  labs,
  briefing,
  projects,
};
